# Non Graded Challenge 4

# Linear Algebra (Matriks)

Nama : Raditya Saputra

Batch : 007 FTDS

# Library yang digunakan numpy

In [1]:
import numpy as np

# Soal nomor 1

- Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \ 99 & 43 \end{bmatrix} \ \begin{bmatrix} 75 & 21 \ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \ 18 & 84 \end{bmatrix} \end{bmatrix} $$

In [33]:
from numpy import array

In [46]:
Tensor = array ([[[23, 50], [7, 12]],
        [[57, 67], [99, 43]],
        [[75, 21], [57, 12]],
        [[87, 26], [18, 84]]])

In [56]:
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [48]:
Tensor.shape

(4, 2, 2)

# Soal nomor 2

- Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

In [49]:
A = np.array ([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
B = np.array ([[17], [22], [19]])

In [50]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [51]:
A.shape

(3, 3)

In [52]:
B

array([[17],
       [22],
       [19]])

In [53]:
B.shape

(3, 1)

In [54]:
hasil_perkalian = A.dot(B)

In [55]:
hasil_perkalian

array([[1852],
       [2454],
       [4305]])

# Soal nomor 3

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

In [59]:
A = np.array ([[23, 50, 19], [7, 12, 109], [57, 67, 98]])

In [60]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

# Transpose

In [61]:
Transpose_A = ('Transpose:\n',A.T)

In [64]:
Transpose_A

('Transpose:\n',
 array([[ 23,   7,  57],
        [ 50,  12,  67],
        [ 19, 109,  98]]))

# Determinan

In [66]:
det_A = np.linalg.det(A)

In [67]:
det_A

131344.0000000002

# Inverse

In [68]:
from numpy.linalg import inv

In [69]:
inv_A = (inv(A))

In [70]:
inv_A

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])